version: '3.8'

x-airflow-common:
  &airflow-common
  build: .
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+pymysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/airflow
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    
    # Custom Environment Variables for Crawler
    ENV: ${ENV:-dev}
    API_KEY: ${API_KEY}
    
    # DB Settings
    DB_HOST: ${DB_HOST:-erdb}
    DB_PORT: ${DB_PORT:-3306}
    DB_NAME: ${DB_NAME:-erdb}
    DB_USER: ${DB_USER:?DB_USER must be set in your .env file}
    DB_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD must be set in your .env file}
    
    # AWS Settings
    AWS_REGION: ${AWS_REGION:-ap-northeast-2}
    AWS_S3_BUCKET: ${AWS_S3_BUCKET}

    DISABLE_FILE_LOGGING: 'true'
    season_id: ${season_id}
    matching_mode: ${matching_mode}
    main_version: ${main_version}
    region_id: ${region_id}
    PYTHONPATH: /opt/airflow:/home/airflow/.local/lib/python3.10/site-packages
  volumes:
    - ./dags:/opt/airflow/dags
    - ./scripts:/opt/airflow/scripts
    - ./config:/opt/airflow/config
    - ./logs:/opt/airflow/logs
    - ./data:/opt/airflow/data
    - ./alembic:/opt/airflow/alembic
    - ./alembic.ini:/opt/airflow/alembic.ini
  user: "${AIRFLOW_UID:-50000}:0"

services:
  erdb:
    image: mysql:8.0
    # 인증 플러그인 호환성 설정
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: airflow     # Airflow용 기본 DB 생성
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-db-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - "3306:3306"

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 5
    restart: always
    depends_on:
      db-migrator:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always
    depends_on:
      db-migrator:
        condition: service_completed_successfully

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
    user: "0:0"
    volumes:
      - .:/sources

volumes:
  mysql-db-volume: 