version: '3.8'

x-airflow-common:
  &airflow-common
  build: .
  environment:
    &airflow-common-env
    TZ: Asia/Seoul
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+pymysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/airflow
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    
    # Custom Environment Variables for Crawler
    ENV: ${ENV:-dev}
    API_KEY: ${API_KEY}
    
    # DB Settings
    DB_HOST: ${DB_HOST:-erdb}
    DB_PORT: ${DB_PORT:-3306}
    DB_NAME: ${DB_NAME:-erdb}
    DB_USER: ${DB_USER:?DB_USER must be set in your .env file}
    DB_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD must be set in your .env file}
    
    # AWS Settings
    AWS_REGION: ${AWS_REGION:-ap-northeast-2}
    AWS_S3_BUCKET: ${AWS_S3_BUCKET}

    DISABLE_FILE_LOGGING: 'true'
    season_id: ${season_id}
    matching_mode: ${matching_mode}
    main_version: ${main_version}
    region_id: ${region_id}
    PYTHONPATH: /opt/airflow:/home/airflow/.local/lib/python3.10/site-packages
  volumes:
    - ./dags:/opt/airflow/dags
    - ./scripts:/opt/airflow/scripts
    - ./config:/opt/airflow/config
    - ./logs:/opt/airflow/logs
    - ./data:/opt/airflow/data
    - ./alembic:/opt/airflow/alembic
    - ./alembic.ini:/opt/airflow/alembic.ini
  user: "${AIRFLOW_UID:-50000}:0"

services:
  erdb:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password # 인증 플러그인 호환성 설정
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: airflow     # Airflow용 기본 DB 생성
    volumes:
      - mysql-db-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - "3307:3306"
  
  # DB 테이블 생성 및 마이그레이션
  db-migrator:
    <<: *airflow-common
    entrypoint: /bin/bash
    command: -c "alembic stamp head"
    restart: on-failure
    depends_on:
      erdb:
        condition: service_healthy

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 5
    restart: always
    depends_on: # DB 테이블 생성 및 마이그레이션이 완료된 후 시작
      db-migrator:
        condition: service_completed_successfully
  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always
    depends_on:
      db-migrator: # 스케줄러도 DB가 준비된 후 시작
        condition: service_completed_successfully
  airflow-init:
    <<: *airflow-common
    depends_on:
      erdb:
        condition: service_healthy
    entrypoint: /bin/bash
    command:
      - -c
      - |
        # Airflow DB 생성
        python3 -c "import pymysql, os; conn = pymysql.connect(host=os.getenv('DB_HOST'), user=os.getenv('DB_USER'), password=os.getenv('DB_PASSWORD')); cursor = conn.cursor(); cursor.execute('CREATE DATABASE IF NOT EXISTS airflow CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci'); conn.close()"

        # airflow dag, log, plugin 초기화 
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
    user: "0:0"
    volumes:
      - .:/sources

volumes:
  mysql-db-volume: 