"""initial_schema_with_composite_keys

Revision ID: 577ea63c5f05
Revises: 
Create Date: 2026-01-09 17:43:34.241630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '577ea63c5f05'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_user_gadget',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('user_num', sa.Integer(), nullable=False),
    sa.Column('gadget_id', sa.Integer(), nullable=False),
    sa.Column('gadget_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id', 'user_num'], ['match_user_start.match_id', 'match_user_start.user_num'], name=op.f('fk_match_user_gadget_match_id_match_user_start')),
    sa.PrimaryKeyConstraint('match_id', 'user_num', 'gadget_id', name=op.f('pk_match_user_gadget'))
    )
    op.drop_index(op.f('armor_name'), table_name='armor_types')
    op.create_unique_constraint(op.f('uq_armor_types_armor_name'), 'armor_types', ['armor_name'])
    op.drop_index(op.f('source_name'), table_name='credit_acquisition_source')
    op.create_unique_constraint(op.f('uq_credit_acquisition_source_source_name'), 'credit_acquisition_source', ['source_name'])
    op.drop_index(op.f('source_name'), table_name='credit_expenditure_source')
    op.create_unique_constraint(op.f('uq_credit_expenditure_source_source_name'), 'credit_expenditure_source', ['source_name'])
    op.drop_constraint(op.f('match_user_combat_ibfk_1'), 'match_user_combat', type_='foreignkey')
    op.drop_constraint(op.f('match_user_combat_ibfk_2'), 'match_user_combat', type_='foreignkey')
    op.create_foreign_key(op.f('fk_match_user_combat_match_id_match_user_start'), 'match_user_combat', 'match_user_start', ['match_id', 'user_num'], ['match_id', 'user_num'])
    op.drop_constraint(op.f('match_user_credit_acquisitions_ibfk_1'), 'match_user_credit_acquisitions', type_='foreignkey')
    op.drop_constraint(op.f('match_user_credit_acquisitions_ibfk_2'), 'match_user_credit_acquisitions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_match_user_credit_acquisitions_match_id_match_user_start'), 'match_user_credit_acquisitions', 'match_user_start', ['match_id', 'user_num'], ['match_id', 'user_num'])
    op.add_column('match_user_credit_expenditures', sa.Column('event_seq', sa.Integer(), nullable=False, comment='Global purchase sequence for user'))
    op.add_column('match_user_credit_expenditures', sa.Column('item_code', sa.Integer(), nullable=True, comment='Raw item code if applicable'))
    op.alter_column('match_user_credit_expenditures', 'expenditure_source_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('match_user_credit_expenditures_ibfk_1'), 'match_user_credit_expenditures', type_='foreignkey')
    op.drop_constraint(op.f('match_user_credit_expenditures_ibfk_2'), 'match_user_credit_expenditures', type_='foreignkey')
    op.create_foreign_key(op.f('fk_match_user_credit_expenditures_match_id_match_user_start'), 'match_user_credit_expenditures', 'match_user_start', ['match_id', 'user_num'], ['match_id', 'user_num'])
    op.drop_column('match_user_credit_expenditures', 'usage_count')
    op.drop_column('match_user_credit_expenditures', 'order_seq')
    op.drop_constraint(op.f('match_user_credit_time_ibfk_1'), 'match_user_credit_time', type_='foreignkey')
    op.drop_constraint(op.f('match_user_credit_time_ibfk_2'), 'match_user_credit_time', type_='foreignkey')
    op.create_foreign_key(op.f('fk_match_user_credit_time_match_id_match_user_start'), 'match_user_credit_time', 'match_user_start', ['match_id', 'user_num'], ['match_id', 'user_num'])
    op.drop_constraint(op.f('match_user_damage_ibfk_2'), 'match_user_damage', type_='foreignkey')
    op.drop_constraint(op.f('match_user_damage_ibfk_1'), 'match_user_damage', type_='foreignkey')
    op.create_foreign_key(op.f('fk_match_user_damage_match_id_match_user_start'), 'match_user_damage', 'match_user_start', ['match_id', 'user_num'], ['match_id', 'user_num'])
    op.drop_constraint(op.f('match_user_end_ibfk_1'), 'match_user_end', type_='foreignkey')
    op.drop_constraint(op.f('match_user_end_ibfk_2'), 'match_user_end', type_='foreignkey')
    op.create_foreign_key(op.f('fk_match_user_end_match_id_match_user_start'), 'match_user_end', 'match_user_start', ['match_id', 'user_num'], ['match_id', 'user_num'])
    op.drop_constraint(op.f('match_user_equipment_ibfk_1'), 'match_user_equipment', type_='foreignkey')
    op.drop_constraint(op.f('match_user_equipment_ibfk_2'), 'match_user_equipment', type_='foreignkey')
    op.create_foreign_key(op.f('fk_match_user_equipment_match_id_match_user_start'), 'match_user_equipment', 'match_user_start', ['match_id', 'user_num'], ['match_id', 'user_num'])
    op.drop_constraint(op.f('match_user_mmr_ibfk_1'), 'match_user_mmr', type_='foreignkey')
    op.drop_constraint(op.f('match_user_mmr_ibfk_2'), 'match_user_mmr', type_='foreignkey')
    op.create_foreign_key(op.f('fk_match_user_mmr_match_id_match_user_start'), 'match_user_mmr', 'match_user_start', ['match_id', 'user_num'], ['match_id', 'user_num'])
    op.drop_constraint(op.f('match_user_object_ibfk_2'), 'match_user_object', type_='foreignkey')
    op.drop_constraint(op.f('match_user_object_ibfk_1'), 'match_user_object', type_='foreignkey')
    op.create_foreign_key(op.f('fk_match_user_object_match_id_match_user_start'), 'match_user_object', 'match_user_start', ['match_id', 'user_num'], ['match_id', 'user_num'])
    op.drop_constraint(op.f('match_user_sight_ibfk_1'), 'match_user_sight', type_='foreignkey')
    op.drop_constraint(op.f('match_user_sight_ibfk_2'), 'match_user_sight', type_='foreignkey')
    op.create_foreign_key(op.f('fk_match_user_sight_match_id_match_user_start'), 'match_user_sight', 'match_user_start', ['match_id', 'user_num'], ['match_id', 'user_num'])
    op.drop_constraint(op.f('match_user_start_ibfk_1'), 'match_user_start', type_='foreignkey')
    op.create_foreign_key(op.f('fk_match_user_start_match_id_match_info'), 'match_user_start', 'match_info', ['match_id'], ['match_id'])
    op.drop_constraint(op.f('match_user_stats_ibfk_2'), 'match_user_stats', type_='foreignkey')
    op.drop_constraint(op.f('match_user_stats_ibfk_1'), 'match_user_stats', type_='foreignkey')
    op.create_foreign_key(op.f('fk_match_user_stats_match_id_match_user_start'), 'match_user_stats', 'match_user_start', ['match_id', 'user_num'], ['match_id', 'user_num'])
    op.drop_constraint(op.f('match_user_trait_ibfk_1'), 'match_user_trait', type_='foreignkey')
    op.drop_constraint(op.f('match_user_trait_ibfk_2'), 'match_user_trait', type_='foreignkey')
    op.create_foreign_key(op.f('fk_match_user_trait_match_id_match_user_start'), 'match_user_trait', 'match_user_start', ['match_id', 'user_num'], ['match_id', 'user_num'])
    op.drop_index(op.f('tactical_skill_name'), table_name='tactical_skills')
    op.create_unique_constraint(op.f('uq_tactical_skills_tactical_skill_name'), 'tactical_skills', ['tactical_skill_name'])
    op.drop_index(op.f('uid'), table_name='user')
    op.create_unique_constraint(op.f('uq_user_uid'), 'user', ['uid'])
    op.drop_index(op.f('weapon_name'), table_name='weapon_types')
    op.create_unique_constraint(op.f('uq_weapon_types_weapon_name'), 'weapon_types', ['weapon_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_weapon_types_weapon_name'), 'weapon_types', type_='unique')
    op.create_index(op.f('weapon_name'), 'weapon_types', ['weapon_name'], unique=True)
    op.drop_constraint(op.f('uq_user_uid'), 'user', type_='unique')
    op.create_index(op.f('uid'), 'user', ['uid'], unique=True)
    op.drop_constraint(op.f('uq_tactical_skills_tactical_skill_name'), 'tactical_skills', type_='unique')
    op.create_index(op.f('tactical_skill_name'), 'tactical_skills', ['tactical_skill_name'], unique=True)
    op.drop_constraint(op.f('fk_match_user_trait_match_id_match_user_start'), 'match_user_trait', type_='foreignkey')
    op.create_foreign_key(op.f('match_user_trait_ibfk_2'), 'match_user_trait', 'match_user_start', ['user_num'], ['user_num'])
    op.create_foreign_key(op.f('match_user_trait_ibfk_1'), 'match_user_trait', 'match_user_start', ['match_id'], ['match_id'])
    op.drop_constraint(op.f('fk_match_user_stats_match_id_match_user_start'), 'match_user_stats', type_='foreignkey')
    op.create_foreign_key(op.f('match_user_stats_ibfk_1'), 'match_user_stats', 'match_user_start', ['match_id'], ['match_id'])
    op.create_foreign_key(op.f('match_user_stats_ibfk_2'), 'match_user_stats', 'match_user_start', ['user_num'], ['user_num'])
    op.drop_constraint(op.f('fk_match_user_start_match_id_match_info'), 'match_user_start', type_='foreignkey')
    op.create_foreign_key(op.f('match_user_start_ibfk_1'), 'match_user_start', 'match_team_info', ['match_id'], ['match_id'])
    op.drop_constraint(op.f('fk_match_user_sight_match_id_match_user_start'), 'match_user_sight', type_='foreignkey')
    op.create_foreign_key(op.f('match_user_sight_ibfk_2'), 'match_user_sight', 'match_user_start', ['user_num'], ['user_num'])
    op.create_foreign_key(op.f('match_user_sight_ibfk_1'), 'match_user_sight', 'match_user_start', ['match_id'], ['match_id'])
    op.drop_constraint(op.f('fk_match_user_object_match_id_match_user_start'), 'match_user_object', type_='foreignkey')
    op.create_foreign_key(op.f('match_user_object_ibfk_1'), 'match_user_object', 'match_user_start', ['match_id'], ['match_id'])
    op.create_foreign_key(op.f('match_user_object_ibfk_2'), 'match_user_object', 'match_user_start', ['user_num'], ['user_num'])
    op.drop_constraint(op.f('fk_match_user_mmr_match_id_match_user_start'), 'match_user_mmr', type_='foreignkey')
    op.create_foreign_key(op.f('match_user_mmr_ibfk_2'), 'match_user_mmr', 'match_user_start', ['user_num'], ['user_num'])
    op.create_foreign_key(op.f('match_user_mmr_ibfk_1'), 'match_user_mmr', 'match_user_start', ['match_id'], ['match_id'])
    op.drop_constraint(op.f('fk_match_user_equipment_match_id_match_user_start'), 'match_user_equipment', type_='foreignkey')
    op.create_foreign_key(op.f('match_user_equipment_ibfk_2'), 'match_user_equipment', 'match_user_start', ['user_num'], ['user_num'])
    op.create_foreign_key(op.f('match_user_equipment_ibfk_1'), 'match_user_equipment', 'match_user_start', ['match_id'], ['match_id'])
    op.drop_constraint(op.f('fk_match_user_end_match_id_match_user_start'), 'match_user_end', type_='foreignkey')
    op.create_foreign_key(op.f('match_user_end_ibfk_2'), 'match_user_end', 'match_user_start', ['user_num'], ['user_num'])
    op.create_foreign_key(op.f('match_user_end_ibfk_1'), 'match_user_end', 'match_user_start', ['match_id'], ['match_id'])
    op.drop_constraint(op.f('fk_match_user_damage_match_id_match_user_start'), 'match_user_damage', type_='foreignkey')
    op.create_foreign_key(op.f('match_user_damage_ibfk_1'), 'match_user_damage', 'match_user_start', ['match_id'], ['match_id'])
    op.create_foreign_key(op.f('match_user_damage_ibfk_2'), 'match_user_damage', 'match_user_start', ['user_num'], ['user_num'])
    op.drop_constraint(op.f('fk_match_user_credit_time_match_id_match_user_start'), 'match_user_credit_time', type_='foreignkey')
    op.create_foreign_key(op.f('match_user_credit_time_ibfk_2'), 'match_user_credit_time', 'match_user_start', ['user_num'], ['user_num'])
    op.create_foreign_key(op.f('match_user_credit_time_ibfk_1'), 'match_user_credit_time', 'match_user_start', ['match_id'], ['match_id'])
    op.add_column('match_user_credit_expenditures', sa.Column('order_seq', mysql.INTEGER(), autoincrement=False, nullable=False, comment='Purchase order in a single match for a user'))
    op.add_column('match_user_credit_expenditures', sa.Column('usage_count', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_match_user_credit_expenditures_match_id_match_user_start'), 'match_user_credit_expenditures', type_='foreignkey')
    op.create_foreign_key(op.f('match_user_credit_expenditures_ibfk_2'), 'match_user_credit_expenditures', 'match_user_start', ['user_num'], ['user_num'])
    op.create_foreign_key(op.f('match_user_credit_expenditures_ibfk_1'), 'match_user_credit_expenditures', 'match_user_start', ['match_id'], ['match_id'])
    op.alter_column('match_user_credit_expenditures', 'expenditure_source_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('match_user_credit_expenditures', 'item_code')
    op.drop_column('match_user_credit_expenditures', 'event_seq')
    op.drop_constraint(op.f('fk_match_user_credit_acquisitions_match_id_match_user_start'), 'match_user_credit_acquisitions', type_='foreignkey')
    op.create_foreign_key(op.f('match_user_credit_acquisitions_ibfk_2'), 'match_user_credit_acquisitions', 'match_user_start', ['user_num'], ['user_num'])
    op.create_foreign_key(op.f('match_user_credit_acquisitions_ibfk_1'), 'match_user_credit_acquisitions', 'match_user_start', ['match_id'], ['match_id'])
    op.drop_constraint(op.f('fk_match_user_combat_match_id_match_user_start'), 'match_user_combat', type_='foreignkey')
    op.create_foreign_key(op.f('match_user_combat_ibfk_2'), 'match_user_combat', 'match_user_start', ['user_num'], ['user_num'])
    op.create_foreign_key(op.f('match_user_combat_ibfk_1'), 'match_user_combat', 'match_user_start', ['match_id'], ['match_id'])
    op.drop_constraint(op.f('uq_credit_expenditure_source_source_name'), 'credit_expenditure_source', type_='unique')
    op.create_index(op.f('source_name'), 'credit_expenditure_source', ['source_name'], unique=True)
    op.drop_constraint(op.f('uq_credit_acquisition_source_source_name'), 'credit_acquisition_source', type_='unique')
    op.create_index(op.f('source_name'), 'credit_acquisition_source', ['source_name'], unique=True)
    op.drop_constraint(op.f('uq_armor_types_armor_name'), 'armor_types', type_='unique')
    op.create_index(op.f('armor_name'), 'armor_types', ['armor_name'], unique=True)
    op.drop_table('match_user_gadget')
    # ### end Alembic commands ###
