"""add_composite_fk_match_team

Revision ID: a07c2af340f3
Revises: 577ea63c5f05
Create Date: 2026-01-10 20:02:32.396400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a07c2af340f3'
down_revision: Union[str, None] = '577ea63c5f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_match_team_info_match_id_team_number",  # 제약조건 이름
        "match_user_start",           # 외래키를 추가할 테이블 (현재 모델을 수정한 테이블)
        "match_team_info",             # 참조할 원본 테이블
        ["match_id", "team_number"],   # 내 테이블 컬럼
        ["match_id", "team_number"]    # 원본 테이블 컬럼
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_match_team_info_match_id_team_number", 
        "match_user_start", 
        type_="foreignkey"
    )
    # ### end Alembic commands ###
