db:
  host: "localhost"
  port: 3306
  user: "your_user"
  database: "eternal_return"
  schema_path: "C:/projects/eternal_return_crawler/db/schema.sql"
api_url:
  base_url: "https://open-api.bser.io"
logging:
  level: INFO
  
header: 
  accept: "application/json"